version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ollama-farm
    binary: ollama-farm
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "ollama-farm_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: danielecalderazzo
    name: ollama-farm
